// One-line editorial mandate per category. Reframes categories as
// newsroom beats rather than blog tags.
const CATEGORY_BEATS: Record<string, string> = {
  AEO: "How answer engines pick what to cite, and what that means for anyone who publishes.",
  AI: "What's actually changing in AI, stripped of the hype cycle around it.",
  "AI Ads": "How AI is rewiring who gets paid for attention online.",
  "AI Browser": "The browser is becoming an agent. This beat tracks what that costs the open web.",
  "AI Compliance": "Where regulation is catching up to AI models, and where it's still years behind.",
  "AI Education": "How students and institutions are actually using AI, not how vendors say they should.",
  "AI FInance": "Money, markets, and the AI systems increasingly deciding both.",
  "AI Food": "AI showing up in kitchens, delivery, and the food industry's supply chain.",
  "AI Health": "AI in medicine and wellness, with the real gains and the real risks kept separate.",
  "AI Infra": "The compute, chips, and data centers holding the entire AI boom up.",
  "AI Mode": "Google's AI-native search experience, tracked feature by feature.",
  "AI Photos": "What AI does to photography, images, and the idea of a real picture.",
  "AI Predictions": "Where this is all heading, with the reasoning shown, not just the guess.",
  "AI Privacy": "What AI systems actually do with your data, versus what they say they do.",
  "AI Robots": "Physical AI: robotics, automation, and machines that act in the real world.",
  "AI Travel": "How AI is changing planning, booking, and the travel industry underneath it.",
  "AI Trolls": "The uglier edge of AI online: manipulation, bots, and bad actors.",
  "AI in Aviation": "AI's expanding role in flight, from booking to the cockpit.",
  "AI in Movies": "What AI means for filmmaking, and what it can't yet replace in it.",
  "AI in Space": "AI's growing footprint in space tech and exploration.",
  "APP ASO": "App store optimization: what actually moves rankings, tested and explained.",
  Arabic: "Coverage for Arabic-speaking readers and markets.",
  Branding: "How brands are built, defended, and occasionally destroyed in public.",
  Climate: "Where technology, business, and climate reality actually intersect.",
  Community: "The people and platforms building real communities online, not just followers.",
  Content: "What actually makes content work, for readers first and algorithms second.",
  "Core Web Vitals": "The technical performance metrics that quietly decide your rankings.",
  Crawling: "How search engines actually crawl and index the web, mechanics included.",
  Explainers: "Complex ideas, broken down properly, with no jargon left unexplained.",
  GPT: "Everything OpenAI ships, tracked as it happens.",
  GenZ: "How the youngest working generation actually uses search, AI, and the internet.",
  "Google AI": "Google's AI products and features, covered as they roll out.",
  "Google Business": "Local search, Business Profiles, and what actually drives foot traffic.",
  "Google Discover": "The traffic source publishers can't control and can't ignore.",
  "Google Play": "Android's app ecosystem and what changes for developers on it.",
  "Google Search": "The core product itself: updates, quirks, and what they mean for you.",
  "Google Updates": "Every algorithm update, decoded before the panic sets in.",
  "Image SEO": "Getting images to actually rank, and to actually load.",
  "Industry News": "What's happening in search and AI, reported straight.",
  "Merchant Centre": "Shopping feeds, product data, and what makes Google trust your listings.",
  "Nano Banana": "Google's experimental image tools, tracked as they evolve.",
  NotebookLM: "Google's AI research tool, and what it's actually useful for.",
  ORM: "Online reputation management: protecting what shows up when someone searches your name.",
  Opinion: "Where the reporting stops and the argument starts.",
  Privacy: "Data, tracking, and consent: what's actually enforced versus performed.",
  Reddit: "Reddit's growing weight in search results and AI training data.",
  Revenue: "What actually converts, monetizes, and pays the bills.",
  SEO: "The fundamentals, still true even as the search landscape shifts under them.",
  Satirical: "Not every truth needs to be delivered straight.",
  "Social Media": "Platforms, algorithms, and the attention economy running underneath them.",
  Startups: "Building in public, the technical and business decisions that actually matter.",
  "Structure Data": "Schema markup and structured data, unglamorous but how you get cited.",
  Uncategorized: "Doesn't fit a beat yet. Still worth reading.",
  Videos: "Video search, YouTube, and the platforms competing for watch time.",
  Windows: "Microsoft's platform moves and what they mean for search and AI.",
  YouTube: "The second-largest search engine, covered like one.",
};

export function categoryBeat(category: string): string | undefined {
  return CATEGORY_BEATS[category];
}
